### ISSUE TITLE
attempt to write data on a closed file object

### ISSUE THREAD

**Issue by dingjiayi** [tokers/lua-io-nginx-module#4]
case is:
1. lua module  main:    (for content_by_lua)
```
local  _M = {}
_M.fd_cache = {}   // cache for file object created by ngx_io.open, key is file_path, val is file object
......
return _M
```
2. create file and cache file object     
```
local  fd1, err = ngx_io.open(file_path1, "a+")
-- do check open ret
_M.fd_cache [file_path1]= fd1
-- fd2, fd3 created like this
```
3. when a request arrived
```
-- get request args
-- get file path to write args , eg: file_path1
--get file object  fd1 = _M.fd_cache[file_path1]
-- call   fd1:write(str_data), then get err: attempt to write data on a closed file object
```
I sure never call fd1:close() in my lua project

Thank you.

**Comment by tokers** [comment]
Hello!

Actually the file object here is related with a specific request, just like the Cosocket object. So the internal resources will be destroyed when the request is closed.

Also, just like Cosocket, DO NOT use a file object cross the request bound.

**Comment by dingjiayi** [comment]
thank you for your reply
